version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 139401680302.dkr.ecr.ap-south-1.amazonaws.com
      - REPO=139401680302.dkr.ecr.ap-south-1.amazonaws.com/devops
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO:latest .
      - docker tag $REPO:latest $REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPO:latest
      - docker push $REPO:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"knownasproto","imageUri":"%s"}]' "$REPO:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
